### ISSUE TITLE
Create extension "Smart Execute for Python"

### ISSUE THREAD

**Issue by chamaoskurumi** [INWTlab/inwt-python-ide#3]
* We need to check whether that is still needed - maybe the Python extension in VSCode now provides smart execute out of the box.
* If Smart Exectue works now out of the Python extension box, we don't need to create our own "Smart Execute for Python" extension.
* There used to be problems with specific smart execute cases [like sending decorators to the REPL](https://github.com/INWTlab/inwt-python-ide#send-decorators-to-the-repl).

**Comment by chamaoskurumi** [comment]
* We tested the plain vscode Python extension using "Shift+Enter" to execute interactively  the https://github.com/INWTlab/inwt-python-ide/blob/main/src/test/interactiveSession.py test file. It works better than a few years ago, but moving to next line and more importantly executing the decorator  still doesn't work
* So we decide to keep our "smart execute with Python" functionality from inwt and turn it into an extension on its own.
* We conduct a few small changes though....

**Comment by wahani** [comment]
See: https://github.com/INWTlab/python-smart-execute

Extension should be published. @chamaoskurumi pls feel free to modify as needed. Creating a tag will trigger a publish to the marketplace automatically.
